GET http://localhost:8082/mbc/read-books/?page=1&limit=10
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiaWQiOiJpcndhbi5kZXYiLCJleHAiOjE3NTU4Njg0ODR9.6VIYT8bWAAUNePoWUsz9BzwJsyj31pydjbIryF6GVwk